# Numpy


In [7]:
import numpy as np

In [8]:
a = np.array([10,20,30,40])

In [9]:
a

array([10, 20, 30, 40])

In [10]:
a[0]

10

In [11]:
a.shape

(4,)

In [12]:
a * 2

array([20, 40, 60, 80])

In [13]:
b = a * 2

In [14]:
b

array([20, 40, 60, 80])

In [15]:
a ** 2

array([ 100,  400,  900, 1600])

In [16]:
mat = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12],[13,14,15,16]])

In [17]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
mat.shape

(4, 4)

In [19]:
mat[0]

array([1, 2, 3, 4])

In [20]:
mat[0][2]

3

In [21]:
mat[2][0]

9

In [22]:
mat[2,2]

11

In [23]:
mat[1:4,0:2]

array([[ 5,  6],
       [ 9, 10],
       [13, 14]])

In [25]:
mat[1:3][1]

array([ 9, 10, 11, 12])

In [26]:
mat[mat % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [27]:
mat[mat > 12]

array([13, 14, 15, 16])

In [28]:
mat[(mat < 10) & (mat > 3)]

array([4, 5, 6, 7, 8, 9])

In [30]:
mat[1][mat[1] % 2 == 0]

array([6, 8])

In [31]:
mat[1]

array([5, 6, 7, 8])

In [32]:
mat[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [33]:
mat[1:,1:][mat[1:,1:] % 2 != 0]

array([ 7, 11, 15])

In [35]:
if (mat > 20).any():
    print("Existe maior do que 3")

In [36]:
if (mat > 20).all():
    print("Todos os valores são menores que 20")

In [37]:
(mat < 20).any()

True

In [38]:
mat.transpose()

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [39]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [40]:
mat2 = mat.transpose()

In [41]:
mat2

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [42]:
mat.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [43]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])

In [44]:
m1.shape

(2, 2)

In [45]:
m2.shape

(2, 2)

In [46]:
m1 * m2

array([[ 5, 12],
       [21, 32]])

In [47]:
m1 + m2

array([[ 6,  8],
       [10, 12]])

In [48]:
m1.sum()

10

In [49]:
m2.sum()

26

In [50]:
mat.sum()

136

In [51]:
m1.sum(axis = 0)

array([4, 6])

In [52]:
m1

array([[1, 2],
       [3, 4]])

In [53]:
m1.sum(axis = 1)

array([3, 7])

In [54]:
m1.shape

(2, 2)

In [55]:
np.reshape(m1,(1,4))

array([[1, 2, 3, 4]])

In [56]:
np.reshape(m1,(4,1))

array([[1],
       [2],
       [3],
       [4]])

In [57]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [59]:
np.reshape(mat,(8,2)).transpose()

array([[ 1,  3,  5,  7,  9, 11, 13, 15],
       [ 2,  4,  6,  8, 10, 12, 14, 16]])

In [60]:
m1

array([[1, 2],
       [3, 4]])

In [62]:
np.append(m1,[[11,9]], axis = 0)

array([[ 1,  2],
       [ 3,  4],
       [11,  9]])

In [63]:
np.append(m1,[[15],[20]], axis = 1)

array([[ 1,  2, 15],
       [ 3,  4, 20]])

In [64]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [65]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [66]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [67]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [68]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [69]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

In [70]:
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [72]:
np.concatenate((a,b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

In [74]:
a = range(0,10)

In [76]:
a  = np.arange(0,10)

In [77]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
np.random.shuffle(a)

In [83]:
a

array([6, 3, 4, 8, 9, 0, 2, 5, 7, 1])

In [84]:
np.linspace(1.0,2.0)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [86]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])