# Numpy


<ul>
    <li>Gerar conjuntos de dados</li>
     <li>Operações em conjuntos de dados</li>
     <li>Slicing (fatiamento) de dados</li>
    <li>Reshape</li>
    <li>Matriz de Os (zeros) e 1s</li>
    <li>Matriz identidade</li>
    <li>Embaralhamento de dados</li>
    <li>Dados em espaço linear</li>
</ul>

                

In [1]:
import numpy as np

In [6]:
a = np.array([10,20,30,40])

In [7]:
a

array([10, 20, 30, 40])

In [9]:
print(a)

[10 20 30 40]


In [10]:
type(a)

numpy.ndarray

In [11]:
a * 2

array([20, 40, 60, 80])

In [13]:
a + 5


array([15, 25, 35, 45])

In [14]:
a ** 2

array([ 100,  400,  900, 1600])

In [15]:
mat = np.array([[i for i in range(1,5)] for j in range(1,5)])

In [18]:
mat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [19]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [22]:
mat = np.array([i for i in range(1,17)])

In [23]:
mat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [24]:
mat = mat.reshape(4,4)

In [25]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [26]:
mat[0]

array([1, 2, 3, 4])

In [27]:
mat[0][0]

1

In [28]:
mat[1][2]

7

In [29]:
mat[0,1]

2

In [32]:
mat[1:3][0]

array([5, 6, 7, 8])

In [33]:
mat[1:,3:]

array([[ 8],
       [12],
       [16]])

In [34]:
mat[-1]

array([13, 14, 15, 16])

In [36]:
mat[:-2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
mat[-2:]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [38]:
mat[mat % 2== 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16])